baseurl = "http://tahar.dev"
defaultcontentlanguage = "en"
languagecode = "en"
theme = "hugo-coder"
title = "Tahar's Blog"

paginate = 20

publishdir = "./docs/"

pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "bw"

googleAnalytics = "G-Z52Z9NGP1T"

[params]
author = "Tahar Meijs"
avatarurl = "images/avatar.png"
description = "Tahar Meijs' personal website"
info = "Software Engineer"
keywords = "blog,developer,personal"

dateFormat = "January 2, 2006"

favicon_16 = "/img/favicon-16x16.png"
favicon_32 = "/img/favicon-32x32.png"

since = 2021

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

[params.utterances]
issueTerm = "pathname"
label = "comment"
repo = "tntmeijs/tntmeijs.github.io"
theme = "photon-dark"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

# Social links
[[params.social]]
icon = "fa fa-github fa-2x"
name = "Github"
url = "https://github.com/tntmeijs/"

[[params.social]]
icon = "fa fa-linkedin fa-2x"
name = "LinkedIn"
url = "https://linkedin.com/in/tntmeijs/"

# Menu links
[[menu.main]]
name = "Blog"
url = "posts/"
weight = 1
[[menu.main]]
name = "Resume"
url = "/files/tahar_meijs_resume.pdf"
weight = 2
[[menu.main]]
name = "About Me"
url = "about/"
weight = 3
