[[collection]]
type = "card"
title = "Breda University of Applied Sciences"
subtitle = "Bachelor of Science (cum laude)"
date = "2016 — 2020"
link = "https://www.buas.nl/en/programmes/creative-media-and-game-technologies/programming"
icon = "/img/buas_logo.png"
content = "Creative Media and Games Technologies with a focus on low-level real-time computer graphics."
